name: 'Power BI VC Utils'
description: 'Prepares Power BI assets for VC.'
author: 'Nathan Giusti'
inputs:
  files:
    description: 'Assets to format'
    required: true
  separator:
    description: 'The character used to seperate file names'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.separator }}
