name: 'Power BI VC Utils'
description: 'Prepares Power BI assets for VC.'
inputs:
  files:
    description: 'Assets to format'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
  