name: 'Deserialize PBIX'
description: 'Prepares Power BI assets for VC.'
author: 'NAZ BeerTech BI Engineering'
inputs:
  files:
    description: 'List of files to format'
    required: true
  separator:
    description: 'The character used to seperate file names'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.separator }}
